# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
main:
  - name: Home
    url: '#about'
    weight: 1
  # - name : About
  #   url : "#about"
  #   parent : Home
  #   weight : 1      
  # - name : Experience
  #   url : "#experience"
  #   parent : Home
  #   weight : 1    
  - name: Publications
    url: '#publications'
    weight: 2   
#  - name : R book
#    url : "#rlibro"
#    weight : 3     
  - name: R book
    url: rlibro/
    weight: 3    
  - name: Projects
    url: '#projects'
    weight: 4  
  - name: People
    url: '#people'
    weight: 5      
  - name: Talks
    url: '#talks'
    weight: 6
  - name: Coursework
    url: '#coursework'
    weight: 7    
  - name: Posts
    url: '#posts'
    weight: 8
  #- name: Contact
  #  url: '#contact'
  #  weight: 9
  - name: Stuff
    identifier: stuff
    url: '#varios'
    weight: 9  
  - name : Experience 
    url : '#experience'
    parent : stuff    
    weight: 1
  - name : Gallery 
    url : '#gallery'
    parent : stuff    
    weight: 2   
  - name : Links 
    url : '#webinteres'
    parent : stuff    
    weight: 3       
  - name : Tags 
    url : '#tags'
    parent : stuff    
    weight: 4   
  - name : Contact 
    url : "#contact"
    parent : stuff
    weight : 5      
  # - name : Experience
  #   url : "#experience"
  #   parent : Home
  #   weight : 1   
  
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70