# Publication types.
# Each item in the list corresponds to an item in the language packs.
# lo modifique el 22 de febrero del 2023, ojo que esto debe
# tener sus mismas definiciones en el archivo "en.yaml" ubicado en el
# path "./wowchemy-hugo-themes/modules/wowchemy/i18n/en.yaml"
types = [ "pub_uncat", #0
          "pub_conf", #1
          "pub_journal", #2
          "pub_preprint", #3
          "pub_report", #4
          "pub_book", #5
          "pub_book_section", #6
          "pub_thesis", #7
          "pub_patent", #8
          "pub_misc" #9
        ]
